"""Typed, replayable record of a Semantic Court deliberation.

The court lets real agents argue, investigate, and cross-examine. This module captures
that debate as a structured, auditable transcript. It never holds a verdict the agents
could fabricate: the outcome it records is the one the deterministic engine already
earned from executed SQL and configured authority. Every turn carries provenance so a
replayed or fallback turn can never be mistaken for a live model turn.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class CourtRole(StrEnum):
    """The roles that speak in the court."""

    ORCHESTRATOR = "orchestrator"
    STEWARD = "steward"
    INVESTIGATOR = "investigator"
    SKEPTIC = "skeptic"
    AUTHORITY = "authority"


class TranscriptMode(StrEnum):
    """How the transcript was produced — never blurred."""

    LIVE_CAPTURED = "live_captured"  # at least one turn was generated by a real model
    REPLAYED = "replayed"  # a sanitized capture replayed deterministically
    DETERMINISTIC_FALLBACK = "deterministic_fallback"  # no model; reviewed fallback text


class TurnProvenance(BaseModel):
    """Where a single turn's words came from."""

    model_config = ConfigDict(frozen=True)

    generated: bool
    provider_name: str
    model: str | None = None
    fallback_reason: str | None = None


class DeliberationTurn(BaseModel):
    """One agent's contribution to the debate."""

    model_config = ConfigDict(frozen=True)

    turn_no: int
    round_no: int
    agent_id: str
    role: CourtRole
    speaking_for: str | None = None
    content: str
    tool_calls: tuple[str, ...] = ()
    cited_evidence_ids: tuple[UUID, ...] = ()
    provenance: TurnProvenance


class DeliberationTranscript(BaseModel):
    """The full, auditable record of one Semantic Court session."""

    model_config = ConfigDict(frozen=True)

    schema_version: str = "1.0"
    term: str
    concept_id: str
    verdict: Literal["conflict", "consistent", "incomplete"]
    outcome: Literal["proposal", "refusal", "no_action"]
    rounds: int
    turns: tuple[DeliberationTurn, ...]
    mode: TranscriptMode
    captured_at: datetime
    content_digest: str

    @property
    def cited_evidence_ids(self) -> tuple[UUID, ...]:
        seen: list[UUID] = []
        for turn in self.turns:
            for evidence_id in turn.cited_evidence_ids:
                if evidence_id not in seen:
                    seen.append(evidence_id)
        return tuple(seen)


def content_digest(
    *,
    term: str,
    concept_id: str,
    verdict: str,
    outcome: str,
    turns: tuple[DeliberationTurn, ...],
) -> str:
    """Deterministic SHA-256 over the meaning of the debate.

    The timestamp and per-turn provenance are excluded so the same debate (live or
    replayed) hashes the same content; the words and cited evidence are what bind it.
    """
    payload = {
        "term": term,
        "concept_id": concept_id,
        "verdict": verdict,
        "outcome": outcome,
        "turns": [
            {
                "turn_no": turn.turn_no,
                "round_no": turn.round_no,
                "agent_id": turn.agent_id,
                "role": turn.role.value,
                "speaking_for": turn.speaking_for,
                "content": turn.content,
                "tool_calls": list(turn.tool_calls),
                "cited_evidence_ids": [str(value) for value in turn.cited_evidence_ids],
            }
            for turn in turns
        ],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def now_utc() -> datetime:
    """A single timestamp source so tests can monkeypatch it if needed."""
    return datetime.now(UTC)
